name: cs230
# Run 
# mamba env update --file environment.yaml 
#to install the packages.
channels:
  - defaults
dependencies:
  - python=3.11
  # for data analysis
  - pandas
  - numpy
  - matplotlib
  - lxml
  # for model
  - pytorch 
  - transformers
  - datasets
  - bitsandbytes
  - accelerate
  - sentencepiece
  # for jupyter notebook
  - jupyter
  - ipykernel
  - ipywidgets
  - widgetsnbextension
  - pandas-profiling
  # for data generation
  - bs4
  - gdown
  # pip install, put your pip packages here
  - pip
  - pip:
    # for .env file
    - python-dotenv
